### ISSUE TITLE
Cache Viewer

### ISSUE THREAD

**Issue by stdavis** [agrc/web-mercator-wsut-killer#10]
Should this just be retired in favor of the preview map on discover.utah.gov?

**Comment by steveoh** [comment]
I love the idea but, I don't know if that will be acceptable. I know bert and zach really like to know what scale level they are at.

**Comment by stdavis** [comment]
@BGranberg & @ZachBeck 
Do you guys still use mapserv.utah.gov/cacheviewer? Or is the preview on discover.agrc.utah.gov suitable? We are looking at which apps we need to upgrade to web mercator and wondered if this one can be dropped. Maybe we should keep it around as long as the UTM base maps are alive?

**Comment by ZachBeck** [comment]
I wouldn't be too broken hearted if it went away. I'll use the cacheviewer
every now and then just for the ease of seeing what cache level is being
displayed, but I can get by with Atlas.

On Mon, Dec 21, 2015 at 7:30 AM, Scott Davis notifications@github.com
wrote:

> @BGranberg https://github.com/BGranberg & @ZachBeck
> https://github.com/ZachBeck
> Do you guys still use mapserv.utah.gov/cacheviewer? Or is the preview on
> discover.agrc.utah.gov suitable? We are looking at which apps we need to
> upgrade to web mercator and wondered if this one can be dropped. Maybe we
> should keep it around as long as the UTM base maps are alive?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/agrc/web-mercator-wsut-killer/issues/10#issuecomment-166317808
> .

## 

```
*Zach Beck*
State of Utah AGRC
zbeck@utah.gov
801 538-3072
```

**Comment by steveoh** [comment]
Sounds like we are going to keep this as is until the UTM maps go away and then kill the service.

**Comment by BGranberg** [comment]
No need to upgrade...but I would love an level or approx scale indicator in
atlas

On Wed, Jan 20, 2016 at 4:10 PM, steveoh notifications@github.com wrote:

> Sounds like we are going to keep this as is until the UTM maps go away and
> then kill the service.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/agrc/web-mercator-wsut-killer/issues/10#issuecomment-173394827
> .

## 

Bert Granberg, Director
Utah Automated Geographic Reference Center (AGRC)
1 State Office Bldg, Rm 5130
Salt Lake City, UT 84114
bgranberg@utah.gov
801 538-3163 (o)
801 558 3563 (m)

**Comment by steveoh** [comment]
@BGranberg add an issue [for atlas](https://github.com/agrc/AGRCJavaScriptProjectBoilerPlate/issues)

**Comment by stdavis** [comment]
I created one: https://github.com/agrc/AGRCJavaScriptProjectBoilerPlate/issues/125
