### ISSUE TITLE
ParcelViewerLoader.js

### ISSUE THREAD

**Issue by stdavis** [agrc/web-mercator-wsut-killer#11]
http://mapserv.utah.gov/cdn/dojo/agrc/1.0/agrc/widgets/viewer/ParcelViewerLoader.js

Used by http://www.grandcountyutah.net/790/Parcel-Viewer-Map

@brigsz Can you check with them to see if this can be replaced with an AGOL map?

**Comment by steveoh** [comment]
this is replaced with #21
