### ISSUE TITLE
Lt Gov Voting Districts Widget

### ISSUE THREAD

**Issue by stdavis** [agrc/web-mercator-wsut-killer#17]

**Comment by steveoh** [comment]
This is also missing it's svn externals.

**Comment by stdavis** [comment]
Looks like it was missing this...
[agrc.zip](https://github.com/agrc/web-mercator-wsut-killer/files/108355/agrc.zip)

**Comment by stdavis** [comment]
@steveoh You never did anything with this, did you? Want to make sure that I don't duplicate efforts.

**Comment by steveoh** [comment]
No I haven't.

**Comment by steveoh** [comment]
wsut removal was deployed to prod today! :shipit: @stdavis

**Comment by stdavis** [comment]
Closed with https://github.com/agrc/lt-gov-political-districts/commit/37fcc109025bd4f2b28b58b5980425b65dc42e9a
