### ISSUE TITLE
Oil Gas Mining

### ISSUE THREAD

**Issue by stdavis** [agrc/web-mercator-wsut-killer#18]

**Comment by steveoh** [comment]
@keatonwalker how are you doing on this? I haven't heard much and I'm hoping you are not stuck.

**Comment by keatonwalker** [comment]
@steveoh I plan to look at it more sometime this week. School is keeping me busy today but I will let you know if I make progress or not.

**Comment by steveoh** [comment]
ok. [this might be important to you](https://github.com/agrc/agrc.widgets/commit/fafcfc118504c613b14f61a7cb0dca99e0f2038e)

**Comment by steveoh** [comment]
@keatonwalker can we get an update on this?

**Comment by stdavis** [comment]
WSUT was shut off on Tuesday which broke the TRS zoom widget for this project. I upgraded the project to remove the dependency on WSUT this morning. Here's the final commit: https://github.com/agrc/oil-gas-mining/commit/416c377a9905db8ed81361c328b63902d457a5fb

This project still needs to be upgraded to web mercator.

**Comment by steveoh** [comment]
thanks for the update scott. :rocket:

**Comment by stdavis** [comment]
Closed with https://github.com/agrc/oil-gas-mining/commit/1fef396c51e7eff81dcfe6b9da7aa202074d3e17
