### ISSUE TITLE
Planning

### ISSUE THREAD

**Issue by stdavis** [agrc/web-mercator-wsut-killer#19]
@brigsz Did we decide that this could not be pushed to AGOL?

**Comment by steveoh** [comment]
WSUT is removed and in production

**Comment by stdavis** [comment]
What ever happened with this app? Two of it's layers have been removed from SGID so I need to update those. However, it's probably not worth it if it's going to AGOL.

**Comment by stdavis** [comment]
From @brigsz

> I am working with Zach to maybe see if he can push it to AGOL.

**Comment by stdavis** [comment]
@brigsz: Did anything ever happen with this?

**Comment by brigsz** [comment]
Nothing has happened with this, I think we should have someone else look at this, and get a plan together to finish it.

**Comment by stdavis** [comment]
Here's the analytics for this app over the last 30 days...
![image](https://cloud.githubusercontent.com/assets/1326248/19898419/871f3642-a021-11e6-9bae-16df91abce4a.png)

I would vote to retire it unless there's someone important that wants it.

**Comment by steveoh** [comment]
Matt suggested shutting this down with an informational page in it's place. @brigsz did you have anything in mind?
