### ISSUE TITLE
SBI

### ISSUE THREAD

**Issue by stdavis** [agrc/web-mercator-wsut-killer#22]
Likely candidate for AGOL. @jpechmann Can you give us an update on this?

**Comment by jpechmann** [comment]
I think we left this at that the app does need to query multiple layers at once for the pop up. I don't know how to do that in AGOL. I'm hoping to work with Michael at some point to figure out how to do that.

One option would be to get the map layers in a basic web app in order to shut this down, and add complexity later. Thoughts? How often is this application used? That would not take me much time.

**Comment by stdavis** [comment]
Looks like it is used fairly regularly by a few visitors:
![image](https://cloud.githubusercontent.com/assets/1326248/11932591/d27bf312-a7b3-11e5-9d30-6cfed11f9c5c.png)

David B would be the one to talk to about whether or not existing functionality in AGOL would be satisfactory. I'm OK keeping this app if it serves a specific purpose that is not easy to fulfill in AGOL or in web app builder.

@jpechmann Would you be willing to talk through the AGOL option with David?

**Comment by steveoh** [comment]
https://subversion.dts.utah.gov/agrc-sbi/ seems to be empty? Where do we have the code for this application?

**Comment by stdavis** [comment]
I'm not sure. It definitely predates GitHub. Did @jpechmann ever talk with David about moving this to AGOL? I think that's a much better solution.

**Comment by steveoh** [comment]
It may be a better solution but it needs to happen sooner than later and if we can kill wsut now then that is a win for us.

**Comment by stdavis** [comment]
@ZachBeck is working on migrating this to AGOL.

**Comment by jpechmann** [comment]
@ZachBeck. Good luck Zach. I got mixed direction from David and Matt on this. Come talk to me if needed.

**Comment by jpechmann** [comment]
Here is a link to the map I had created in AGOL: http://arcg.is/1QGL8hl.

**Comment by steveoh** [comment]
Will someone know what this means?
![image](https://cloud.githubusercontent.com/assets/325813/13089685/1401dc02-d4af-11e5-978e-d2f840294369.png)

or are those supposed to be these values?
![image](https://cloud.githubusercontent.com/assets/325813/13089767/72ca3e78-d4af-11e5-9280-bcd565389b85.png)

**Comment by jpechmann** [comment]
This isn't the final product. I was waiting on a few requirements to be worked out. It sounds like @ZachBeck is taking over.

**Comment by steveoh** [comment]
> Situation Awareness widget – This widget enables you to create or select an incident on the map and analyze information from feature layers either within the incident area or within a specified distance of the incident.

from https://blogs.esri.com/esri/arcgis/2016/02/29/whats-new-in-web-appbuilder-for-arcgis-march-2016/

I wonder if this will allow you to query all the layers at a POI.

**Comment by steveoh** [comment]
WSUT is replaced. There are issues with Web Mercator for a Web App Builder (WAB) project being hosted on mapserv with the discover server in AGOL using the regex for AGOL only. The project is in UTM for now until we can either update the AGOL regex to include mapserv or figure out a better solution.

**Comment by brigsz** [comment]
@steveoh Is your comment on Jul 6 still valid?  Is there something I can do on this?

**Comment by steveoh** [comment]
we need to ask Rick to add mapserv to the key that sbi is using more that we can update quad words.

**Comment by steveoh** [comment]
nurse-figure-pretend-joshua is available when we make this change.

**Comment by steveoh** [comment]
SBI is web mercator
