### ISSUE TITLE
Roadkill

### ISSUE THREAD

**Issue by stdavis** [agrc/web-mercator-wsut-killer#24]
I don't think that we need to touch the mobile app since it doesn't display data and is hooked directly to the SDE data which will remain in UTM.

Desktop app may need to be moved from pointing directly at SDE to a file geodatabase that has reprojected data.

**Comment by stdavis** [comment]
Still need to switch to web mercator...

**Comment by stdavis** [comment]
:confetti_ball:

**Comment by steveoh** [comment]
👏
