### ISSUE TITLE
platmap.trustlands.utah.gov

### ISSUE THREAD

**Issue by stdavis** [agrc/web-mercator-wsut-killer#26]
Need to contact Barry about getting this upgraded. This may be the app that they don't have the source code for. Not sure.

**Comment by steveoh** [comment]
> 12:37:26 PM Steve Gourley: Hey Barry, how is that update of the platmap website going?
> 12:40:49 PM Barry Biediger: couple of wrenches thrown into the works
> 12:41:00 PM Barry Biediger: two people quit
> 12:41:28 PM Barry Biediger: hope to get going on it again in january
> 12:41:46 PM Steve Gourley: oh fun, i noticed that there are requests to the WSUT service still
> 12:42:11 PM Steve Gourley: i assume that is only for the trs stuff?
> 12:42:16 PM Barry Biediger: i thought we git everything updated
> 12:42:22 PM Barry Biediger: got
> 12:42:40 PM Barry Biediger: how long do we have ?
> 12:43:00 PM Steve Gourley: looks like it's the place names search
> 12:43:17 PM Steve Gourley: well that depends, i think matt sent out an email that said jan 2016
> 12:43:33 PM Barry Biediger: Yah, i seem to remember that.
> 12:43:48 PM Steve Gourley: trs looks good
> 12:43:50 PM Barry Biediger: You helped me update the other things, right?
> 12:43:53 PM Steve Gourley: its the place name search
> 12:44:02 PM Barry Biediger: I think I can get it updated
> 12:44:05 PM Steve Gourley: i don't remember
> 12:44:28 PM Barry Biediger: maybe next weeK (if it isn't hidden in their built code
> 12:44:34 PM Barry Biediger: I don't think it is
> 12:44:55 PM Barry Biediger: I think they just modified your widget
> 12:45:44 PM Steve Gourley: if it's using find generic https://github.com/agrc/agrc.widgets/blob/master/widgets/locate/FindGeneric.js
> 12:45:48 PM Barry Biediger: They've put some strange, useless stuff in their .net code, probably so we'd have to pay them to fix things
> 12:46:07 PM Steve Gourley: you could switch to https://github.com/agrc/agrc.widgets/blob/master/widgets/locate/MagicZoom.js
> 12:46:14 PM Barry Biediger: K.  I'll look into it.
> 12:55:28 PM Steve Gourley: Thanks. Let me know if you need anything
> 12:58:11 PM Barry Biediger: k thanks
> 12:59:27 PM Steve Gourley: watch out for 
> 
> /WSUT/FeatureGeometry.svc/GetEnvelope/trssearch-widget/layer(SGID10.CADASTRE.PLSSTownships_GCDB)where(LABEL)(=)('T35S+R12W'+AND+BASEMERIDIAN+=+'26')quotes=false as a request also
> 1:05:50 PM Barry Biediger: is that still being called from trs search?
> 1:05:54 PM Steve Gourley: appears so
> 1:06:04 PM Barry Biediger: k
> 1:06:05 PM Steve Gourley: this is from the last 2 weeks
> 1:11:02 PM Barry Biediger: I don't understand why that would be coming through when the other trs calls have been updated. It looks like a normal call from the widget
> 1:12:56 PM Steve Gourley: i think the final request to zoom uses the old url
> 1:15:47 PM Barry Biediger: Ah OK
> 1:16:03 PM Barry Biediger: It'll be nice to get away from that crappy app
> 1:40:46 PM Steve Gourley: yeah i know the feeling

**Comment by brigsz** [comment]
I believe that Barry confirmed with both Steve and I on separate occasions that he has made the necessary changes, I believe this can be closed.
