### ISSUE TITLE
Uptime Monitor for mapserv.utah.gov

### ISSUE THREAD

**Issue by stdavis** [agrc/web-mercator-wsut-killer#27]
Do we just need to switch off the monitoring on WSUT or does it need to be repointed at the web api?

**Comment by steveoh** [comment]
Should be pointed at the web api.

**Comment by steveoh** [comment]
@brigsz can you get a list of the monitoring we currently have. We may be able to delete the WSUT if the web api is already tested.

**Comment by brigsz** [comment]
Yes, I will get a ticket started on this.  Wow, this sounds strangely
familiar, like we looked at this.....I will get the list

**Comment by brigsz** [comment]
I believe this is complete, is there a way to confirm this?  Steve is this what we had Neal fix?

**Comment by steveoh** [comment]
I can shut down the service and wait for uptime to complain. Our next test with Katie is the 20th. I say we close it and reopen if the monitor fires when we work with Katie.
