### ISSUE TITLE
Geolocators on mapserv

### ISSUE THREAD

**Issue by stdavis** [agrc/web-mercator-wsut-killer#31]
Coordinate with the webapi.

**Comment by steveoh** [comment]
I'm not sure if these need to be changed. Anything that has the ability to set the output SR should be safe .

**Comment by stdavis** [comment]
Only issue that I can see is performance if the majority of the requests going to the geocoding webapi are for 3857.

**Comment by steveoh** [comment]
I doubt the majority of geocoding requests will be in the presentation layer spatial reference. I would assume most will stay in UTM with the source data.

**Comment by stdavis** [comment]
Fair enough.
