### ISSUE TITLE
LandMobileRadio service

### ISSUE THREAD

**Issue by stdavis** [agrc/web-mercator-wsut-killer#34]
The app is currently not up. Does this service get used?

**Comment by brigsz** [comment]
I will check in on this one and see what is appropriate

**Comment by stdavis** [comment]
@brigsz Is this project still alive?

**Comment by brigsz** [comment]
Hard to know, as the person pushing it was forced to resign based on the admin secretary committing fraud.  It is still a discussion that is happening at UCA, but at this point I am unsure, though I do believe people will have questions about it when the legislative session starts.  There is a debate on which technology to go with for radio service

**Comment by stdavis** [comment]
Here's the usage for this service over the last 30 days:
![image](https://cloud.githubusercontent.com/assets/1326248/16654572/a9d1c002-4413-11e6-8c61-8bd1d1c3d86e.png)
Not sure who would be hitting it since the app isn't up. I would recommend that we shut this service off and bring it back up if people ask for it in the future.

**Comment by brigsz** [comment]
I am unable to find this embedded anywhere on the UCA site.  They are the primary customer.  Yes, lets shut down the service

**Comment by stdavis** [comment]
Done.
