### ISSUE TITLE
Socrata service on mapserv

### ISSUE THREAD

**Issue by stdavis** [agrc/web-mercator-wsut-killer#35]
I don't think that there should be any problems converting this service to WGS. May need to republish it to Socrata.

**Comment by steveoh** [comment]
This is handled in forklift and is ready to be converted whenever someone says to do so.

**Comment by stdavis** [comment]
Republished this service pointing to web mercator forklift data. New `Socrata.mxd` is in `C:\ClusterStorage\Volume1`.
