### ISSUE TITLE
UtahPLSS Basemap Cache

### ISSUE THREAD

**Issue by stdavis** [agrc/web-mercator-wsut-killer#36]
http://mapserv.utah.gov/arcgis/rest/services/UtahPLSS/MapServer

**Comment by stdavis** [comment]
Did some experimenting with using Vector tiles (hosted in AGOL) for this in deq. Have some issues with the labels but it's looking like a good possibility.

**Comment by stdavis** [comment]
Here's the vector tiles in production: http://tiles.arcgis.com/tiles/99lidPhWCzftIe9K/arcgis/rest/services/UtahPLSS/VectorTileServer

DEQ is using them in production. Still a few issues with duplicate labels being removed.

We should probably wait on closing this issue until we shut down the old service.

**Comment by steveoh** [comment]
I saw that printing of vector tiles does not work. Something to keep in mind.

**Comment by stdavis** [comment]
Confirmed that printing vector tiles doesn't work on enviro.utah.gov. :(

**Comment by steveoh** [comment]
you'll have to swap it out for the raster or vector data.

**Comment by steveoh** [comment]
@stdavis are you still using the vector tiles in production? I'd like to convert PLSS and will take a dependency on the VT's if the thought is that we will continue to maintain it.

**Comment by stdavis** [comment]
Yes, I consider that service production. Michael moved it to be under the main AGRC account. However, that being said, I'm not sure that we have a update plan for it. I'll put it on my base map updates list.

**Comment by steveoh** [comment]
We will need a plan as there are big updates coming next month from the fabric etc. I stopped the UtahPLSS cache service tonight.

**Comment by stdavis** [comment]
For now I've added it to the [basemap updates spreadsheet](https://docs.google.com/spreadsheets/d/1XnncmhWrIjntlaMfQnMrlcCTyl9e2i-ztbvqryQYXDc/edit#gid=0). This will keep it from falling through the cracks.

At some point in the future we could script the updating of it via a forklift pallet.
