### ISSUE TITLE
http://grantreporting.udaf.utah.gov/Public   wrong basemap

### ISSUE THREAD

**Issue by brigsz** [agrc/web-mercator-wsut-killer#40]
Failed to load resource: the server responded with a status of 404 (Not Found)

http://mapserv.utah.gov/ArcGIS/rest/services/BaseMaps/Hybrid/MapServer?f=json&callback=dojo.io.script.jsonp_dojoIoScript1._jsonpCallback

**Comment by steveoh** [comment]
this is mostly fixed. I need some extra eyes on the dojo build from @stdavis but other than that we have a working page again.
