### ISSUE TITLE
roads.utah.gov

### ISSUE THREAD

**Issue by stdavis** [agrc/web-mercator-wsut-killer#6]
This is the PLPCO app. Needs to be upgraded to their 10.3 server also.

**Comment by steveoh** [comment]
This app never had its external dependencies checked in and the `svn:externals` property is empty. @stdavis do you have a local copy of this project with the dependencies resolved?

**Comment by stdavis** [comment]
[Archive.zip](https://github.com/agrc/web-mercator-wsut-killer/files/104986/Archive.zip)

**Comment by steveoh** [comment]
> 10:58:42 AM Steve: Hey Jason
> 10:59:05 AM Steve: we are removing/updating some deprecated web service calls from some websites we have created
> 10:59:10 AM Steve: I'm looking at roads.utah.gov now
> 10:59:34 AM Steve: and the township range section search tool is using the deprecated web service
> 11:01:44 AM Steve: The feature classes that tool is using were removed from the 93 database around 2 months ago and the 93 database is on it's way out the door
> Changed status to Online (11:01:51 AM)
> 11:02:17 AM Steve: My question to you is, did you notice it was broken? Do you use that search tool? Is it worth spending time to update or should I remove it and move on?
> 11:03:16 AM Jason Wolf: No complaints about it missing here, so my guess is no one has used it 
> 11:03:38 AM Steve: ok, i'll remove it. Thanks Jason.

**Comment by stdavis** [comment]
:+1:

**Comment by stdavis** [comment]
New non-WSUT version pushed to production and is looking good.

**Comment by stdavis** [comment]
:confetti_ball: :confetti_ball: :confetti_ball:
